# Generated by Django 4.0.2 on 2022-03-04 09:11

import PrintableDesignManager.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, default=None, editable=False, max_length=255, null=True)),
                ('source', models.URLField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, default=None, editable=False, max_length=255, null=True)),
                ('md5sum', models.CharField(blank=True, db_index=True, default=None, max_length=50, null=True, unique=True)),
                ('width', models.FloatField(blank=True, default=None, null=True)),
                ('height', models.FloatField(blank=True, default=None, null=True)),
                ('depth', models.FloatField(blank=True, default=None, null=True)),
                ('file', models.FileField(upload_to=PrintableDesignManager.models.part_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PrintableDesignManager.design')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, default=None, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Render',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=PrintableDesignManager.models.render_directory_path)),
                ('camera_yaw', models.IntegerField()),
                ('camera_pitch', models.IntegerField()),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PrintableDesignManager.part')),
            ],
        ),
        migrations.CreateModel(
            name='PartsToDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PrintableDesignManager.design')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PrintableDesignManager.part')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('md5sum', models.CharField(blank=True, db_index=True, default=None, max_length=50, null=True)),
                ('file', models.FileField(upload_to=PrintableDesignManager.models.document_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PrintableDesignManager.design')),
                ('type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='PrintableDesignManager.documenttype')),
            ],
        ),
        migrations.AddField(
            model_name='design',
            name='parts',
            field=models.ManyToManyField(related_name='DesignToPart', through='PrintableDesignManager.PartsToDesign', to='PrintableDesignManager.Part'),
        ),
        migrations.AddField(
            model_name='design',
            name='vendor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='PrintableDesignManager.vendor'),
        ),
    ]
