# Generated by Django 4.0.2 on 2022-03-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrintableDesignManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
