# Generated by Django 4.0.2 on 2022-03-07 18:46

import PrintableDesignManager.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PrintableDesignManager', '0002_alter_design_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, default=None, editable=False, max_length=255, null=True)),
                ('url', models.URLField(blank=True, default=None, null=True)),
                ('file', models.FileField(upload_to=PrintableDesignManager.models.document_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='VendorNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='design',
            name='commercial_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='slug',
            field=models.SlugField(blank=True, default=None, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='license',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='PrintableDesignManager.licence'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='notes',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='PrintableDesignManager.vendornotes'),
        ),
    ]
