# Generated by Django 4.0.2 on 2022-03-07 18:54

import PrintableDesignManager.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PrintableDesignManager', '0003_licence_vendornotes_design_commercial_use_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendornotes',
            options={'get_latest_by': 'created_at', 'ordering': ['vendor', 'created_at']},
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='notes',
        ),
        migrations.AddField(
            model_name='vendornotes',
            name='vendor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='PrintableDesignManager.vendor'),
        ),
        migrations.AlterField(
            model_name='licence',
            name='file',
            field=models.FileField(upload_to=PrintableDesignManager.models.licence_directory_path),
        ),
    ]
