# Generated by Django 4.0.2 on 2022-03-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrintableDesignManager', '0004_alter_vendornotes_options_remove_vendor_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='design',
            unique_together={('name', 'vendor')},
        ),
    ]
