# Generated by Django 4.0.2 on 2022-03-08 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrintableDesignManager', '0005_alter_design_name_alter_design_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='part',
            unique_together={('md5sum', 'design')},
        ),
    ]
