# Generated by Django 4.0.2 on 2022-03-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrintableDesignManager', '0006_alter_part_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='md5sum',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=50, null=True),
        ),
    ]
